### ISSUE TITLE
Add configuration for basic htpp authentication set via 

### ISSUE THREAD

**Issue by pzaich** [docktermj/senzing-docker-python-flask-rest-api#18]
We would like to see the Flask application extended to support [basic http authentication](https://www.pivotaltracker.com/story/show/162422243) set via environment variables in the docker image. Basic authentication could be an optional feature turned on when certain env vars are present. This gives us the option to tighten access to the api service. 

The environment variables could map to something like this:

`SENZING_API_USERNAME`
`SENZING_API_PASSWORD`

**Comment by docktermj** [comment]
Have working version in a branch:  https://github.com/docktermj/senzing-docker-python-flask-rest-api/tree/issue-1.dockter.1

Will be delivering to master branch later today.   

Test cases
```
export SENZING_BASIC_AUTH_USERNAME=bob-username
export SENZING_BASIC_AUTH_PASSWORD=bob-password

cd ${REPOSITORY}/app
./app.py

# Fails
curl -v -X GET \
  http://localhost:5000/ping

# Succeeds
curl -v -X GET \
  --user bob-username:bob-password \
  http://localhost:5000/ping

# Fails
curl -v -X GET \
  --user mary-username:mary-password \
  http://localhost:5000/ping
```

**Comment by docktermj** [comment]
Included in https://github.com/docktermj/senzing-docker-python-flask-rest-api/pull/20
