### ISSUE TITLE
Requesting the entity of a missing record results in a 500 error

### ISSUE THREAD

**Issue by pzaich** [docktermj/senzing-docker-python-flask-rest-api#19]
Requesting the entity of a missing record (e.g. `https://application_root/records/PEOPLE/123/entity`)  currently returns a 500 error. A 404 Not Found status would be more applicable when a record is missing.

**Comment by docktermj** [comment]
https://github.com/docktermj/senzing-docker-python-flask-rest-api/pull/21

**Comment by docktermj** [comment]
Closed by pull request #21
